INSERT INTO `countries` (`id`, `code`, `name`, `phonecode`,`flag`) VALUES
(1, 'AF' , '{"en":"Afghanistan"}' , 93 ,'/flags/flag-of-Afghanistan.jpg'),
(2, 'AL' , '{"en":"Albania"}' , 355 ,'/flags/flag-of-Albania.jpg'),
(3, 'DZ' , '{"en":"Algeria"}' , 213 ,'/flags/flag-of-Algeria.jpg'),
(4, 'AS' , '{"en":"American Samoa"}' , 1684 ,''),
(5, 'AD' , '{"en":"Andorra"}' , 376 ,'/flags/flag-of-Andorra.jpg'),
(6, 'AO' , '{"en":"Angola"}' , 244 ,'/flags/flag-of-Angola.jpg'),
(7, 'AI' , '{"en":"Anguilla"}' , 1264 ,''),
(8, 'AQ' , '{"en":"Antarctica"}' , 0 ,''),
(9, 'AG' , '{"en":"Antigua And Barbuda"}' , 1268 ,'/flags/flag-of-Antigua.jpg'),
(10, 'AR' , '{"en":"Argentina"}' , 54 ,'/flags/flag-of-Argentina.jpg'),
(11, 'AM' , '{"en":"Armenia"}' , 374 ,'/flags/flag-of-Armenia.jpg'),
(12, 'AW' , '{"en":"Aruba"}' , 297 ,''),
(13, 'AU' , '{"en":"Australia"}' , 61 ,'/flags/flag-of-Australia.jpg'),
(14, 'AT' , '{"en":"Austria"}' , 43 ,'/flags/flag-of-Austria.jpg'),
(15, 'AZ' , '{"en":"Azerbaijan"}' , 994 ,'/flags/flag-of-Azerbaijan.jpg'),
(16, 'BS' , '{"en":"Bahamas The"}' , 1242 ,'/flags/flag-of-Bahamas.jpg'),
(17, 'BH' , '{"en":"Bahrain"}' , 973 ,'/flags/flag-of-Bahrain.jpg'),
(18, 'BD' , '{"en":"Bangladesh"}' , 880 ,'/flags/flag-of-Bangladesh.jpg'),
(19, 'BB' , '{"en":"Barbados"}' , 1246 ,'/flags/flag-of-Barbados.jpg'),
(20, 'BY' , '{"en":"Belarus"}' , 375 ,'/flags/flag-of-Belarus.jpg'),
(21, 'BE' , '{"en":"Belgium"}' , 32 ,'/flags/flag-of-Belgium.jpg'),
(22, 'BZ' , '{"en":"Belize"}' , 501 ,'/flags/flag-of-Belize.jpg'),
(23, 'BJ' , '{"en":"Benin"}' , 229 ,'/flags/flag-of-Benin.jpg'),
(24, 'BM' , '{"en":"Bermuda"}' , 1441 ,''),
(25, 'BT' , '{"en":"Bhutan"}' , 975 ,'/flags/flag-of-Bhutan.jpg'),
(26, 'BO' , '{"en":"Bolivia"}' , 591 ,'/flags/flag-of-Bolivia.jpg'),
(27, 'BA' , '{"en":"Bosnia and Herzegovina"}' , 387 ,'/flags/flag-of-Bosnia-Herzegovina.jpg'),
(28, 'BW' , '{"en":"Botswana"}' , 267 ,'/flags/flag-of-Botswana.jpg'),
(29, 'BV' , '{"en":"Bouvet Island"}' , 0 ,''),
(30, 'BR' , '{"en":"Brazil"}' , 55 ,'/flags/flag-of-Brazil.jpg'),
(31, 'IO' , '{"en":"British Indian Ocean Territory"}' , 246 ,''),
(32, 'BN' , '{"en":"Brunei"}' , 673 ,'/flags/flag-of-Brunei.jpg'),
(33, 'BG' , '{"en":"Bulgaria"}' , 359 ,'/flags/flag-of-Bulgaria.jpg'),
(34, 'BF' , '{"en":"Burkina Faso"}' , 226 ,'/flags/flag-of-Burkina-Faso.jpg'),
(35, 'BI' , '{"en":"Burundi"}' , 257 ,'/flags/flag-of-Burundi.jpg'),
(36, 'KH' , '{"en":"Cambodia"}' , 855 ,'/flags/flag-of-Cambodia.jpg'),
(37, 'CM' , '{"en":"Cameroon"}' , 237 ,'/flags/flag-of-Cameroon.jpg'),
(38, 'CA' , '{"en":"Canada"}' , 1 ,'/flags/flag-of-Canada.jpg'),
(39, 'CV' , '{"en":"Cape Verde"}' , 238 ,'/flags/flag-of-Cabo-Verde.jpg'),
(40, 'KY' , '{"en":"Cayman Islands"}' , 1345 ,''),
(41, 'CF' , '{"en":"Central African Republic"}' , 236 ,'/flags/flag-of-Central-African-Republic.jpg'),
(42, 'TD' , '{"en":"Chad"}' , 235 ,'/flags/flag-of-Chad.jpg'),
(43, 'CL' , '{"en":"Chile"}' , 56 ,'/flags/flag-of-Chile.jpg'),
(44, 'CN' , '{"en":"China"}' , 86 ,'/flags/flag-of-China.jpg'),
(45, 'CX' , '{"en":"Christmas Island"}' , 61 ,''),
(46, 'CC' , '{"en":"Cocos (Keeling) Islands"}' , 672 ,''),
(47, 'CO' , '{"en":"Colombia"}' , 57 ,'/flags/flag-of-Colombia.jpg'),
(48, 'KM' , '{"en":"Comoros"}' , 269 ,'/flags/flag-of-Comoros.jpg'),
(49, 'CG' , '{"en":"Republic Of The Congo"}' , 242 ,'/flags/flag-of-Congo.jpg'),
(50, 'CD' , '{"en":"Democratic Republic Of The Congo"}' , 242 ,'/flags/flag-of-Congo-Democratic-Republic-of.jpg'),
(51, 'CK' , '{"en":"Cook Islands"}' , 682 ,''),
(52, 'CR' , '{"en":"Costa Rica"}' , 506 ,'/flags/flag-of-Costa-Rica.jpg'),
(53, 'CI' , '{"en":"Cote D Ivoire (Ivory Coast)"}' , 225 ,'/flags/flag-of-Cote-d-Ivoire.jpg'),
(54, 'HR' , '{"en":"Croatia (Hrvatska)"}' , 385 ,'/flags/flag-of-Croatia.jpg'),
(55, 'CU' , '{"en":"Cuba"}' , 53 ,'/flags/flag-of-Cuba.jpg'),
(56, 'CY' , '{"en":"Cyprus"}' , 357 ,'/flags/flag-of-Cyprus.jpg'),
(57, 'CZ' , '{"en":"Czech Republic"}' , 420 ,'/flags/flag-of-Czech-Republic.jpg'),
(58, 'DK' , '{"en":"Denmark"}' , 45 ,'/flags/flag-of-Denmark.jpg'),
(59, 'DJ' , '{"en":"Djibouti"}' , 253 ,'/flags/flag-of-Djibouti.jpg'),
(60, 'DM' , '{"en":"Dominica"}' , 1767 ,'/flags/flag-of-Dominica.jpg'),
(61, 'DO' , '{"en":"Dominican Republic"}' , 1809 ,'/flags/flag-of-Dominican-Republic.jpg'),
(62, 'TP' , '{"en":"East Timor"}' , 670 ,''),
(63, 'EC' , '{"en":"Ecuador"}' , 593 ,'/flags/flag-of-Ecuador.jpg'),
(64, 'EG' , '{"en":"Egypt"}' , 20 , '/flags/flag-of-Egypt.jpg'),
(65, 'SV' , '{"en":"El Salvador"}' , 503 ,'/flags/flag-of-El-Salvador.jpg'),
(66, 'GQ' , '{"en":"Equatorial Guinea"}' , 240 ,'/flags/flag-of-Equatorial-Guinea.jpg'),
(67, 'ER' , '{"en":"Eritrea"}' , 291 ,'/flags/flag-of-Eritrea.jpg'),
(68, 'EE' , '{"en":"Estonia"}' , 372 ,'/flags/flag-of-Estonia.jpg'),
(69, 'ET' , '{"en":"Ethiopia"}' , 251 ,'/flags/flag-of-Ethiopia.jpg'),
(70, 'XA' , '{"en":"External Territories of Australia"}' , 61 ,''),
(71, 'FK' , '{"en":"Falkland Islands"}' , 500 ,''),
(72, 'FO' , '{"en":"Faroe Islands"}' , 298 ,''),
(73, 'FJ' , '{"en":"Fiji Islands"}' , 679 ,'/flags/flag-of-Fiji.jpg'),
(74, 'FI' , '{"en":"Finland"}' , 358 ,'/flags/flag-of-Finland.jpg'),
(75, 'FR' , '{"en":"France"}' , 33 ,'/flags/flag-of-France.jpg'),
(76, 'GF' , '{"en":"French Guiana"}' , 594 ,''),
(77, 'PF' , '{"en":"French Polynesia"}' , 689 ,''),
(78, 'TF' , '{"en":"French Southern Territories"}' , 0 ,''),
(79, 'GA' , '{"en":"Gabon"}' , 241 ,'/flags/flag-of-Gabon.jpg'),
(80, 'GM' , '{"en":"Gambia The"}' , 220 ,'/flags/flag-of-Gambia.jpg'),
(81, 'GE' , '{"en":"Georgia"}' , 995 ,'/flags/flag-of-Georgia.jpg'),
(82, 'DE' , '{"en":"Germany"}' , 49 ,'/flags/flag-of-Germany.jpg'),
(83, 'GH' , '{"en":"Ghana"}' , 233 ,'/flags/flag-of-Ghana.jpg'),
(84, 'GI' , '{"en":"Gibraltar"}' , 350 ,''),
(85, 'GR' , '{"en":"Greece"}' , 30 ,'/flags/flag-of-Greece.jpg'),
(86, 'GL' , '{"en":"Greenland"}' , 299 ,''),
(87, 'GD' , '{"en":"Grenada"}' , 1473 ,'/flags/flag-of-Grenada.jpg'),
(88, 'GP' , '{"en":"Guadeloupe"}' , 590 ,''),
(89, 'GU' , '{"en":"Guam"}' , 1671 ,''),
(90, 'GT' , '{"en":"Guatemala"}' , 502 ,'/flags/flag-of-Guatemala.jpg'),
(91, 'XU' , '{"en":"Guernsey and Alderney"}' , 44 ,''),
(92, 'GN' , '{"en":"Guinea"}' , 224 ,'/flags/flag-of-Guinea.jpg'),
(93, 'GW' , '{"en":"Guinea-Bissau"}' , 245 ,'/flags/flag-of-Guinea-Bissau.jpg'),
(94, 'GY' , '{"en":"Guyana"}' , 592 ,'/flags/flag-of-Guyana.jpg'),
(95, 'HT' , '{"en":"Haiti"}' , 509 ,'/flags/flag-of-Haiti.jpg'),
(96, 'HM' , '{"en":"Heard and McDonald Islands"}' , 0 ,''),
(97, 'HN' , '{"en":"Honduras"}' , 504 ,'/flags/flag-of-Honduras.jpg'),
(98, 'HK' , '{"en":"Hong Kong S.A.R."}' , 852 ,''),
(99, 'HU' , '{"en":"Hungary"}' , 36 ,'/flags/flag-of-Hungary.jpg'),
(100, 'IS' , '{"en":"Iceland"}' , 354 ,'/flags/flag-of-Iceland.jpg'),
(101, 'IN' , '{"en":"India"}' , 91 ,'/flags/flag-of-India.jpg'),
(102, 'ID' , '{"en":"Indonesia"}' , 62 ,'/flags/flag-of-Indonesia.jpg'),
(103, 'IR' , '{"en":"Iran"}' , 98 ,'/flags/flag-of-Iran.jpg'),
(104, 'IQ' , '{"en":"Iraq"}' , 964 ,'/flags/flag-of-Iraq.jpg'),
(105, 'IE' , '{"en":"Ireland"}' , 353 ,'/flags/flag-of-Ireland.jpg'),
(106, 'IL' , '{"en":"Israel"}' , 972 ,'/flags/flag-of-Israel.jpg'),
(107, 'IT' , '{"en":"Italy"}' , 39 ,'/flags/flag-of-Italy.jpg'),
(108, 'JM' , '{"en":"Jamaica"}' , 1876 ,'/flags/flag-of-Jamaica.jpg'),
(109, 'JP' , '{"en":"Japan"}' , 81 ,'/flags/flag-of-Japan.jpg'),
(110, 'XJ' , '{"en":"Jersey"}' , 44 ,''),
(111, 'JO' , '{"en":"Jordan"}' , 962 ,'/flags/flag-of-Jordan.jpg'),
(112, 'KZ' , '{"en":"Kazakhstan"}' , 7 ,'/flags/flag-of-Kazakhstan.jpg'),
(113, 'KE' , '{"en":"Kenya"}' , 254 ,'/flags/flag-of-Kenya.jpg'),
(114, 'KI' , '{"en":"Kiribati"}' , 686 ,'/flags/flag-of-Kiribati.jpg'),
(115, 'KP' , '{"en":"Korea North"}' , 850 ,'/flags/flag-of-Korea-North.jpg'),
(116, 'KR' , '{"en":"Korea South"}' , 82 ,'/flags/flag-of-Korea-South.jpg'),
(117, 'KW' , '{"en":"Kuwait"}' , 965 , '/flags/flag-of-Kuwait.jpg'),
(118, 'KG' , '{"en":"Kyrgyzstan"}' , 996 ,'/flags/flag-of-Kyrgyzstan.jpg'),
(119, 'LA' , '{"en":"Laos"}' , 856 ,'/flags/flag-of-Laos.jpg'),
(120, 'LV' , '{"en":"Latvia"}' , 371 ,'/flags/flag-of-Latvia.jpg'),
(121, 'LB' , '{"en":"Lebanon"}' , 961 ,'/flags/flag-of-Lebanon.jpg'),
(122, 'LS' , '{"en":"Lesotho"}' , 266 ,'/flags/flag-of-Lesotho.jpg'),
(123, 'LR' , '{"en":"Liberia"}' , 231 ,'/flags/flag-of-Liberia.jpg'),
(124, 'LY' , '{"en":"Libya"}' , 218 ,'/flags/flag-of-Libya.jpg'),
(125, 'LI' , '{"en":"Liechtenstein"}' , 423 ,'/flags/flag-of-Liechtenstein.jpg'),
(126, 'LT' , '{"en":"Lithuania"}' , 370 ,'/flags/flag-of-Lithuania.jpg'),
(127, 'LU' , '{"en":"Luxembourg"}' , 352 ,'/flags/flag-of-Luxembourg.jpg'),
(128, 'MO' , '{"en":"Macau S.A.R."}' , 853 ,''),
(129, 'MK' , '{"en":"Macedonia"}' , 389 ,'/flags/flag-of-Macedonia.jpg'),
(130, 'MG' , '{"en":"Madagascar"}' , 261 ,'/flags/flag-of-Madagascar.jpg'),
(131, 'MW' , '{"en":"Malawi"}' , 265 ,'/flags/flag-of-Malawi.jpg'),
(132, 'MY' , '{"en":"Malaysia"}' , 60 ,'/flags/flag-of-Malaysia.jpg'),
(133, 'MV' , '{"en":"Maldives"}' , 960 ,'/flags/flag-of-Maldives.jpg'),
(134, 'ML' , '{"en":"Mali"}' , 223 ,'/flags/flag-of-Mali.jpg'),
(135, 'MT' , '{"en":"Malta"}' , 356 ,'/flags/flag-of-Malta.jpg'),
(136, 'XM' , '{"en":"Man (Isle of)"}' , 44 ,''),
(137, 'MH' , '{"en":"Marshall Islands"}' , 692 ,'/flags/flag-of-Marshall-Islands.jpg'),
(138, 'MQ' , '{"en":"Martinique"}' , 596 ,''),
(139, 'MR' , '{"en":"Mauritania"}' , 222 ,'/flags/flag-of-Mauritania.jpg'),
(140, 'MU' , '{"en":"Mauritius"}' , 230 ,'/flags/flag-of-Mauritius.jpg'),
(141, 'YT' , '{"en":"Mayotte"}' , 269 ,''),
(142, 'MX' , '{"en":"Mexico"}' , 52 ,'/flags/flag-of-Mexico.jpg'),
(143, 'FM' , '{"en":"Micronesia"}' , 691 ,'/flags/flag-of-Micronesia.jpg'),
(144, 'MD' , '{"en":"Moldova"}' , 373 ,'/flags/flag-of-Moldova.jpg'),
(145, 'MC' , '{"en":"Monaco"}' , 377 ,'/flags/flag-of-Monaco.jpg'),
(146, 'MN' , '{"en":"Mongolia"}' , 976 ,'/flags/flag-of-Mongolia.jpg'),
(147, 'MS' , '{"en":"Montserrat"}' , 1664 ,''),
(148, 'MA' , '{"en":"Morocco"}' , 212 ,'/flags/flag-of-Morocco.jpg'),
(149, 'MZ' , '{"en":"Mozambique"}' , 258 ,'/flags/flag-of-Mozambique.jpg'),
(150, 'MM' , '{"en":"Myanmar"}' , 95 ,'/flags/flag-of-Myanmar.jpg'),
(151, 'NA' , '{"en":"Namibia"}' , 264 ,'/flags/flag-of-Namibia.jpg'),
(152, 'NR' , '{"en":"Nauru"}' , 674 ,'/flags/flag-of-Nauru.jpg'),
(153, 'NP' , '{"en":"Nepal"}' , 977 ,'/flags/flag-of-Nepal.jpg'),
(154, 'AN' , '{"en":"Netherlands Antilles"}' , 599 ,'/flags/flag-of-Netherlands.jpg'),
(155, 'NL' , '{"en":"Netherlands The"}' , 31 ,'/flags/flag-of-Netherlands.jpg'),
(156, 'NC' , '{"en":"New Caledonia"}' , 687 ,''),
(157, 'NZ' , '{"en":"New Zealand"}' , 64 ,'/flags/flag-of-New-Zealand.jpg'),
(158, 'NI' , '{"en":"Nicaragua"}' , 505 ,'/flags/flag-of-Nicaragua.jpg'),
(159, 'NE' , '{"en":"Niger"}' , 227 ,'/flags/flag-of-Niger.jpg'),
(160, 'NG' , '{"en":"Nigeria"}' , 234 ,'/flags/flag-of-Nigeria.jpg'),
(161, 'NU' , '{"en":"Niue"}' , 683 ,''),
(162, 'NF' , '{"en":"Norfolk Island"}' , 672 ,''),
(163, 'MP' , '{"en":"Northern Mariana Islands"}' , 1670 ,''),
(164, 'NO' , '{"en":"Norway"}' , 47 ,'/flags/flag-of-Norway.jpg'),
(165, 'OM' , '{"en":"Oman"}' , 968 ,'/flags/flag-of-Oman.jpg'),
(166, 'PK' , '{"en":"Pakistan"}' , 92 ,'/flags/flag-of-Pakistan.jpg'),
(167, 'PW' , '{"en":"Palau"}' , 680 ,'/flags/flag-of-Palau.jpg'),
(168, 'PS' , '{"en":"Palestinian Territory Occupied"}' , 970 ,'/flags/flag-of-Palestine.jpg'),
(169, 'PA' , '{"en":"Panama"}' , 507 ,'/flags/flag-of-Panama.jpg'),
(170, 'PG' , '{"en":"Papua new Guinea"}' , 675 ,'/flags/flag-of-Papua-New-Guinea.jpg'),
(171, 'PY' , '{"en":"Paraguay"}' , 595 ,'/flags/flag-of-Paraguay.jpg'),
(172, 'PE' , '{"en":"Peru"}' , 51 ,'/flags/flag-of-Peru.jpg'),
(173, 'PH' , '{"en":"Philippines"}' , 63 ,'/flags/flag-of-Philippines.jpg'),
(174, 'PN' , '{"en":"Pitcairn Island"}' , 0 ,''),
(175, 'PL' , '{"en":"Poland"}' , 48 ,'/flags/flag-of-Poland.jpg'),
(176, 'PT' , '{"en":"Portugal"}' , 351 ,'/flags/flag-of-Portugal.jpg'),
(177, 'PR' , '{"en":"Puerto Rico"}' , 1787 ,''),
(178, 'QA' , '{"en":"Qatar"}' , 974 ,'/flags/flag-of-Qatar.jpg'),
(179, 'RE' , '{"en":"Reunion"}' , 262 ,''),
(180, 'RO' , '{"en":"Romania"}' , 40 ,'/flags/flag-of-Romania.jpg'),
(181, 'RU' , '{"en":"Russia"}' , 70 ,'/flags/flag-of-Russia.jpg'),
(182, 'RW' , '{"en":"Rwanda"}' , 250 ,'/flags/flag-of-Rwanda.jpg'),
(183, 'SH' , '{"en":"Saint Helena"}' , 290 ,''),
(184, 'KN' , '{"en":"Saint Kitts And Nevis"}' , 1869 ,''),
(185, 'LC' , '{"en":"Saint Lucia"}' , 1758 ,''),
(186, 'PM' , '{"en":"Saint Pierre and Miquelon"}' , 508 ,''),
(187, 'VC' , '{"en":"Saint Vincent And The Grenadines"}' , 1784 ,''),
(188, 'WS' , '{"en":"Samoa"}' , 684 ,'/flags/flag-of-Samoa.jpg'),
(189, 'SM' , '{"en":"San Marino"}' , 378 ,'/flags/flag-of-San-Marino.jpg'),
(190, 'ST' , '{"en":"Sao Tome and Principe"}' , 239 ,'/flags/flag-of-Sao-Tome-and-Principe.jpg'),
(191, 'SA' , '{"en":"Saudi Arabia"}' , 966 , '/flags/flag-of-Saudi-Arabia.jpg'),
(192, 'SN' , '{"en":"Senegal"}' , 221 ,'/flags/flag-of-Senegal.jpg'),
(193, 'RS' , '{"en":"Serbia"}' , 381 ,'/flags/flag-of-Serbia.jpg'),
(194, 'SC' , '{"en":"Seychelles"}' , 248 ,'/flags/flag-of-Seychelles.jpg'),
(195, 'SL' , '{"en":"Sierra Leone"}' , 232 ,'/flags/flag-of-Sierra-Leone.jpg'),
(196, 'SG' , '{"en":"Singapore"}' , 65 ,'/flags/flag-of-Singapore.jpg'),
(197, 'SK' , '{"en":"Slovakia"}' , 421 ,'/flags/flag-of-Slovakia.jpg'),
(198, 'SI' , '{"en":"Slovenia"}' , 386 ,'/flags/flag-of-Slovenia.jpg'),
(199, 'XG' , '{"en":"Smaller Territories of the UK"}' , 44 ,''),
(200, 'SB' , '{"en":"Solomon Islands"}' , 677 ,'/flags/flag-of-Solomon-Islands.jpg'),
(201, 'SO' , '{"en":"Somalia"}' , 252 ,'/flags/flag-of-Somalia.jpg'),
(202, 'ZA' , '{"en":"South Africa"}' , 27 ,'/flags/flag-of-South-Africa.jpg'),
(203, 'GS' , '{"en":"South Georgia"}' , 0 ,''),
(204, 'SS' , '{"en":"South Sudan"}' , 211 ,'/flags/flag-of-South-Sudan.jpg'),
(205, 'ES' , '{"en":"Spain"}' , 34 ,'/flags/flag-of-Spain.jpg'),
(206, 'LK' , '{"en":"Sri Lanka"}' , 94 ,'/flags/flag-of-Sri-Lanka.jpg'),
(207, 'SD' , '{"en":"Sudan"}' , 249 ,'/flags/flag-of-Sudan.jpg'),
(208, 'SR' , '{"en":"Suriname"}' , 597 ,'/flags/flag-of-Suriname.jpg'),
(209, 'SJ' , '{"en":"Svalbard And Jan Mayen Islands"}' , 47 ,''),
(210, 'SZ' , '{"en":"Swaziland"}' , 268 ,'/flags/flag-of-Swaziland.jpg'),
(211, 'SE' , '{"en":"Sweden"}' , 46 ,'/flags/flag-of-Sweden.jpg'),
(212, 'CH' , '{"en":"Switzerland"}' , 41 ,'/flags/flag-of-Switzerland.jpg'),
(213, 'SY' , '{"en":"Syria"}' , 963 ,'/flags/flag-of-Syria.jpg'),
(214, 'TW' , '{"en":"Taiwan"}' , 886 ,'/flags/flag-of-Taiwan.jpg'),
(215, 'TJ' , '{"en":"Tajikistan"}' , 992 ,'/flags/flag-of-Tajikistan.jpg'),
(216, 'TZ' , '{"en":"Tanzania"}' , 255 ,'/flags/flag-of-Tanzania.jpg'),
(217, 'TH' , '{"en":"Thailand"}' , 66 ,'/flags/flag-of-Thailand.jpg'),
(218, 'TG' , '{"en":"Togo"}' , 228 ,'/flags/flag-of-Togo.jpg'),
(219, 'TK' , '{"en":"Tokelau"}' , 690 ,''),
(220, 'TO' , '{"en":"Tonga"}' , 676 ,'/flags/flag-of-Tonga.jpg'),
(221, 'TT' , '{"en":"Trinidad And Tobago"}' , 1868 ,'/flags/flag-of-Trinidad-and-Tobago.jpg'),
(222, 'TN' , '{"en":"Tunisia"}' , 216 ,'/flags/flag-of-Tunisia.jpg'),
(223, 'TR' , '{"en":"Turkey"}' , 90 ,'/flags/flag-of-Turkey.jpg'),
(224, 'TM' , '{"en":"Turkmenistan"}' , 7370 ,'/flags/flag-of-Turkmenistan.jpg'),
(225, 'TC' , '{"en":"Turks And Caicos Islands"}' , 1649 ,''),
(226, 'TV' , '{"en":"Tuvalu"}' , 688 ,'/flags/flag-of-Tuvalu.jpg'),
(227, 'UG' , '{"en":"Uganda"}' , 256 ,'/flags/flag-of-Uganda.jpg'),
(228, 'UA' , '{"en":"Ukraine"}' , 380 ,'/flags/flag-of-Ukraine.jpg'),
(229, 'AE' , '{"en":"United Arab Emirates"}' , 971 ,'/flags/flag-of-United-Arab-Emirates.jpg'),
(230, 'GB' , '{"en":"United Kingdom"}' , 44 ,'/flags/flag-of-United-Kingdom.jpg'),
(231, 'US' , '{"en":"United States"}' , 1 ,'/flags/flag-of-United-States-of-America.jpg'),
(232, 'UM' , '{"en":"United States Minor Outlying Islands"}' , 1 ,''),
(233, 'UY' , '{"en":"Uruguay"}' , 598 ,'/flags/flag-of-Uruguay.jpg'),
(234, 'UZ' , '{"en":"Uzbekistan"}' , 998 ,'/flags/flag-of-Uzbekistan.jpg'),
(235, 'VU' , '{"en":"Vanuatu"}' , 678 ,'/flags/flag-of-Vanuatu.jpg'),
(236, 'VA' , '{"en":"Vatican City State (Holy See)"}' , 39 ,'/flags/flag-of-Vatican-City.jpg'),
(237, 'VE' , '{"en":"Venezuela"}' , 58 ,'/flags/flag-of-Venezuela.jpg'),
(238, 'VN' , '{"en":"Vietnam"}' , 84 ,'/flags/flag-of-Vietnam.jpg'),
(239, 'VG' , '{"en":"Virgin Islands (British)"}' , 1284 ,''),
(240, 'VI' , '{"en":"Virgin Islands (US)"}' , 1340 ,''),
(241, 'WF' , '{"en":"Wallis And Futuna Islands"}' , 681 ,''),
(242, 'EH' , '{"en":"Western Sahara"}' , 212 ,''),
(243, 'YE' , '{"en":"Yemen"}' , 967 ,'/flags/flag-of-Yemen.jpg'),
(244, 'YU' , '{"en":"Yugoslavia"}' , 38 ,''),
(245, 'ZM' , '{"en":"Zambia"}' , 260 ,'/flags/flag-of-Zambia.jpg'),
(246, 'ZW' , '{"en":"Zimbabwe"}' , 263 ,'/flags/flag-of-Zimbabwe.jpg');



