INSERT INTO `dynamic_pages` (`id`, `title`, `slug`, `description`, `status`, `is_static`,`created_at`,`updated_at`) VALUES
(1, '{"en":"About Us"}', 'about-us', '{"en":"initial description"}', 1, 0, NOW(), NOW()),
(3, '{"en":"Blog"}', 'blog', '{"en":"initial description"}', 1, 1, NOW(), NOW()),
(4, '{"en":"Become A Merchant"}', 'merchant', '{"en":"initial description"}', 1, 1, NOW(), NOW()),
(5, '{"en":"My Account"}', 'profile', '{"en":"initial description"}', 1, 1, NOW(), NOW()),
(6, '{"en":"My Orders"}', 'my-purchase-orders', '{"en":"initial description"}', 1, 1, NOW(), NOW()),
(7, '{"en":"My Cart"}', 'cart', '{"en":"initial description"}', 1, 1, NOW(), NOW()),
(8, '{"en":"My Wish List"}', 'my-wishlist', '{"en":"initial description"}', 1, 1, NOW(), NOW()),
(9, '{"en":"Refunds & Disputes"}', 'refund/my-refund-list', '{"en":"initial description"}', 1, 1, NOW(), NOW()),
(10, '{"en":"My Coupons"}', 'profile/coupons', '{"en":"initial description"}', 1, 1, NOW(), NOW()),
(11, '{"en":"My Wallet"}', 'wallet/customer/my-wallet-index', '{"en":"initial description"}', 1, 1, NOW(), NOW()),
(12, '{"en":"Referral"}', 'profile/referral', '{"en":"initial description"}', 1, 1, NOW(), NOW()),
(13, '{"en":"Help & Contact Us"}', 'contact-us', '{"en":"initial description"}', 1, 1, NOW(), NOW()),
(14, '{"en":"Track Orders"}', 'track-order', '{"en":"initial description"}', 1, 1, NOW(), NOW()),
(15, '{"en":"Support Tickets"}', 'support-ticket', '{"en":"initial description"}', 1, 1, NOW(), NOW()),
(16, '{"en":"Compare"}', 'compare', '{"en":"initial description"}', 1, 1, NOW(), NOW()),
(17, '{"en":"Dashboard"}', 'profile/dashboard', '{"en":"initial description"}', 1, 1, NOW(), NOW()),
(18, '{"en":"Shopping Recent Viewed"}', 'shopping-recent-viewed', '{"en":"initial description"}', 1, 1, NOW(), NOW()),
(19, '{"en":"My Giftcarts"}', 'purchased-gift-cards', '{"en":"initial description"}', 1, 1, NOW(), NOW()),
(20, '{"en":"My Digital Products"}', 'digital-products', '{"en":"initial description"}', 1, 1, NOW(), NOW()),
(21, '{"en":"Return & Exchange"}', 'return-exchange', '{"en":"initial description"}', 1, 1, NOW(), NOW());
